kind: CronJob
apiVersion: batch/v1
metadata:
  name: "{{ required "cronJobName must be set!" .Values.cronJobName }}"
  namespace: "{{ required "Namespace must be set!" .Values.namespace }}"
spec:
  concurrencyPolicy: "Replace"
  schedule: {{ required "Schedule must be set!" .Values.schedule | quote }}
  suspend: false
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.retriesBeforeFailure }}
      parallelism: 1
      completions: 1
      template:
        spec:
          {{- if .Values.podRoleArn }}
          serviceAccountName: {{ .Values.cronJobName }}
          {{- end }}
          restartPolicy: {{ if eq (int .Values.retriesBeforeFailure) 0 }}Never{{ else }}OnFailure{{ end }}
          imagePullSecrets:
            - name: docker.pkg.github.com
            - name: ghcr.io
          containers:
            - name: "{{ .Values.cronJobName }}"
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              {{- if gt (len .Values.args) 0 }}
              args:
{{ toYaml .Values.args | indent 14 }}
              {{- end }}
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: {{ required "CPU guarantee must be set!" .Values.resources.cpu.guarantee }}
                  memory: {{ required "Memory requirement must be set!" .Values.resources.memory }}
                limits:
                {{- if .Values.resources.cpu.limit }}
                  cpu: {{ .Values.resources.cpu.limit }}
                {{- end }}
                  memory: {{ required "Memory requirement must be set!" .Values.resources.memory }}

              env:
                {{- range $key, $value := .Values.env.fromSecret }}
                - name: "{{ $key }}"
                  valueFrom:
                    secretKeyRef:
                      name: "{{ $.Values.cronJobName }}-external-secret"
                      key: "{{ $key }}"
                {{- end }}
                {{- range $key, $value := .Values.env.additional }}
                - name: {{ $key }}
{{ toYaml $value | indent 18 }}
                {{- end }}
