# how to call cronJob
cronJobName: ""

# namespace to use, typically team-<yourteamname>
namespace: ""


# schedule to run in cronjob-format, see https://crontab.guru/ e.g. "25 1 * * */2"
schedule: ""

# how often to re-attempt running the job (at each scheduled point in time) - keep at 0, if the job should be run only once
retriesBeforeFailure: 0

# what Docker image to run
image:
  repository: "" # example: ghcr.io/itdesign-gmbh/mp-templatetiger/mp-templatetiger
  tag: "" # Tag is normally configured during deployment

# list of startup argument(s) for the job
args: []

# k8s resource definitions for required minimum and maximum growth
resources:
  memory: 64Mi
  cpu:
    guarantee: 100m

env:
  fromSecret: {}
  #  SOME_SECRET:
  #    parameterName: other-system/secret

  # custom k8s env definition
  additional: {}
  #  SOME_VARIABLE:
  #    value: 'some-value'

