{{- if .Values.prometheusScraping }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: "{{ .Values.serviceName }}"
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Values.serviceName }}"
  podMetricsEndpoints:
    - port: management
      path: /actuator/prometheus
{{- end }}
