{{- if and .Values.env.springDatasourceFromSecret .Values.env.springDatasourceFromSecretWithRLS }}
{{ fail "You cannot set both springDatasourceFromSecret and springDatasourceFromSecretWithRLS at the same time" }}
{{- end}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceName }}-external-secret
spec:
  backendType: systemManager
  roleArn: {{ required "secretsRoleArn must be set!" .Values.secretsRoleArn }}
  data:
    - name: "SENTRY_DSN"
      key: "/{{ required "clusterName must be set!" .Values.clusterName }}/sentry/dsn-{{ .Values.serviceName }}"
    - name: "SERVICE_OAUTH2_PUBLIC_KEY"
      key: "/{{ .Values.clusterName }}/authenticorn/public-key"
  {{- if .Values.env.springDatasourceFromSecret }}
    - name: "SPRING_DATASOURCE_URL"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecret }}/jdbc-url"
    - name: "SPRING_DATASOURCE_USERNAME"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecret }}/username"
    - name: "SPRING_DATASOURCE_PASSWORD"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecret }}/password"
  {{- else if .Values.env.springDatasourceFromSecretWithRLS }}
    - name: "SPRING_DATASOURCE_URL"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecretWithRLS }}/jdbc-url"
    - name: "SPRING_DATASOURCE_USERNAME"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecretWithRLS }}/rls-username"
    - name: "SPRING_DATASOURCE_PASSWORD"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecretWithRLS }}/rls-password"
    - name: "SPRING_FLYWAY_USER"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecretWithRLS }}/username"
    - name: "SPRING_FLYWAY_PASSWORD"
      key: "/{{ .Values.clusterName }}/{{ .Values.env.springDatasourceFromSecretWithRLS }}/password"
  {{- end }}
  {{- if .Values.env.springRabbitMQSecret }}
    - name: "SPRING_RABBITMQ_HOST"
      key: "/{{ .Values.clusterName }}/rabbitmq/hostname"
    - name: "SPRING_RABBITMQ_USERNAME"
      key: "/{{ .Values.clusterName }}/rabbitmq/username"
    - name: "SPRING_RABBITMQ_PASSWORD"
      key: "/{{ .Values.clusterName }}/rabbitmq/password"
  {{- end }}
   {{- if .Values.ingress.basicAuthSecretParameterName }}
    - name: "auth"
      key: "/{{ .Values.clusterName }}/{{ .Values.ingress.basicAuthSecretParameterName }}"
  {{- end }}
  {{- range $key, $value := .Values.env.fromSecret }}
    - name: "{{ $key }}"
      key: "/{{ $.Values.clusterName }}/{{ $value.parameterName }}"
  {{- end }}
