{{- if .Values.podRoleArn }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: '{{ .Values.podRoleArn }}'
{{- end }}
