{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: 'arn:aws:iam::{{ .Values.awsAccountId | required "awsAccountId needs to be set to create a serviceAccount!" }}:role/k8s-{{ .Values.envName }}-{{ .Values.serviceName }}'
{{- end }}
