{{- define "get-platform-secret-keys" }}
{{- $platform := include "get-platform" . }}
{{- if eq $platform "spring" }}
  {{- if .Values.platform.spring.env.oAuth2PublicKey }}
- secretKey: "SERVICE_OAUTH2_PUBLIC_KEY"
  remoteRef:
    key: "/{{ .Values.envName }}/authenticorn/public-key"
  {{- end }}
  {{- if .Values.platform.spring.env.datasourceFromSecret }}
- secretKey: "DATASOURCE_URL"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/jdbc-url"
- secretKey: "DATASOURCE_USERNAME"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/username"
- secretKey: "DATASOURCE_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/password"
  {{- else if .Values.platform.spring.env.datasourceFromSecretWithRLS }}
- secretKey: "DATASOURCE_URL"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/jdbc-url"
- secretKey: "DATASOURCE_USERNAME"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/rls-username"
- secretKey: "DATASOURCE_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/rls-password"
- secretKey: "DATASOURCE_PRIVILEGED_CONNECTION_USER"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/username"
- secretKey: "DATASOURCE_PRIVILEGED_CONNECTION_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/password"
  {{- end }}
  {{- if .Values.platform.spring.env.rabbitMQSecret }}
- secretKey: "RABBITMQ_HOST"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/hostname"
- secretKey: "RABBITMQ_SSL_ENABLED"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/ssl"
- secretKey: "RABBITMQ_USERNAME"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/username"
- secretKey: "RABBITMQ_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/password"
  {{- end }}
{{- else if eq $platform "nodejs" }}
  {{- if .Values.platform.nodejs.env.oAuth2PublicKey }}
- secretKey: "SERVICE_OAUTH2_PUBLIC_KEY"
  remoteRef:
    key: "/{{ .Values.envName }}/authenticorn/public-key"
  {{- end }}
  {{- if .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}
- secretKey: "DATASOURCE_URL"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}/jdbc-url"
- secretKey: "DATASOURCE_USERNAME"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}/rls-username"
- secretKey: "DATASOURCE_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}/rls-password"
- secretKey: "DATASOURCE_PRIVILEGED_CONNECTION_USER"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}/username"
- secretKey: "DATASOURCE_PRIVILEGED_CONNECTION_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/{{ .Values.platform.nodejs.env.datasourceFromSecretWithRLS }}/password"
  {{- end }}
  {{- if .Values.platform.nodejs.env.rabbitMQSecret }}
- secretKey: "RABBITMQ_HOST"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/hostname"
- secretKey: "RABBITMQ_SSL_ENABLED"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/ssl"
- secretKey: "RABBITMQ_USERNAME"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/username"
- secretKey: "RABBITMQ_PASSWORD"
  remoteRef:
    key: "/{{ .Values.envName }}/rabbitmq/password"
  {{- end }}
{{- else if eq $platform "python" }}
{{- else if eq $platform "nginx" }}
{{- else }}{{ fail (printf "Platform %s: Envs not defined" $platform) }}
{{- end }}
{{- end }}
