{{- if eq (include "get-platform" .) "spring" }}
{{- if and .Values.platform.spring.env.datasourceFromSecret .Values.platform.spring.env.datasourceFromSecretWithRLS }}
{{ fail "You cannot set both springDatasourceFromSecret and springDatasourceFromSecretWithRLS at the same time" }}
{{- end}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  data:
    {{- if .Values.sentry.enabled }}
    - secretKey: "SENTRY_DSN"
      remoteRef:
        key: "/{{ required "envName must be set!" .Values.envName }}/sentry/dsn-{{ .Release.Name }}"
    {{- end }}
    - secretKey: "SERVICE_OAUTH2_PUBLIC_KEY"
      remoteRef:
        key: "/{{ .Values.envName }}/authenticorn/public-key"
  {{- if .Values.platform.spring.env.datasourceFromSecret }}
    - secretKey: "SPRING_DATASOURCE_URL"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/jdbc-url"
    - secretKey: "SPRING_DATASOURCE_USERNAME"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/username"
    - secretKey: "SPRING_DATASOURCE_PASSWORD"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecret }}/password"
  {{- else if .Values.platform.spring.env.datasourceFromSecretWithRLS }}
    - secretKey: "SPRING_DATASOURCE_URL"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/jdbc-url"
    - secretKey: "SPRING_DATASOURCE_USERNAME"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/rls-username"
    - secretKey: "SPRING_DATASOURCE_PASSWORD"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/rls-password"
    - secretKey: "SPRING_FLYWAY_USER"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/username"
    - secretKey: "SPRING_FLYWAY_PASSWORD"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.platform.spring.env.datasourceFromSecretWithRLS }}/password"
  {{- end }}
  {{- if .Values.platform.spring.env.rabbitMQSecret }}
    - secretKey: "SPRING_RABBITMQ_HOST"
      remoteRef:
        key: "/{{ .Values.envName }}/rabbitmq/hostname"
    - secretKey: "SPRING_RABBITMQ_SSL_ENABLED"
      remoteRef:
        key: "/{{ .Values.envName }}/rabbitmq/ssl"
    - secretKey: "SPRING_RABBITMQ_USERNAME"
      remoteRef:
        key: "/{{ .Values.envName }}/rabbitmq/username"
    - secretKey: "SPRING_RABBITMQ_PASSWORD"
      remoteRef:
        key: "/{{ .Values.envName }}/rabbitmq/password"
  {{- end }}
   {{- if .Values.ingress.basicAuthSecretParameterName }}
    - secretKey: "auth"
      remoteRef:
        key: "/{{ .Values.envName }}/{{ .Values.ingress.basicAuthSecretParameterName }}"
  {{- end }}
  {{- range $key, $value := .Values.podConfiguration.env.fromSecret }}
    - secretKey: "{{ $key }}"
      remoteRef:
        key: "/{{ $.Values.envName }}/{{ $value.parameterName }}"
  {{- end }}
{{- end }}
