{{- if .Values.env.fromSecret }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.cronJobName }}-external-secret
spec:
  backendType: systemManager
  roleArn: {{ required "secretsRoleArn must be set!" .Values.secretsRoleArn }}
  data:
  {{- range $key, $value := .Values.env.fromSecret }}
    - name: "{{ $key }}"
      key: "/{{ $.Values.clusterName }}/{{ $value.parameterName }}"
  {{- end }}
{{- end }}
