{{- if .Values.env.fromSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.cronJobName }}-external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  data:
  {{- range $key, $value := .Values.env.fromSecret }}
    - secretKey: "{{ $key }}"
      remoteRef:
        key: "/{{ $.Values.envName }}/{{ $value.parameterName }}"
  {{- end }}
{{- end }}
