{{- if (ne (include "is-ingress-public-defined" .) "false") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-public
  namespace: "{{ required "Namespace must be set!" .Values.namespace }}"
  annotations:
    {{- if .Values.ingress.overwriteCustomHttpErrors }}
    nginx.ingress.kubernetes.io/custom-http-errors: {{ .Values.ingress.overwriteCustomHttpErrors }}
    {{- end }}
    {{- if .Values.ingress.overwriteProxyReadTimeout }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.overwriteProxyReadTimeout }}
    {{- end }}
    {{- if .Values.ingress.overwriteCustomBodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.overwriteCustomBodySize }}
    {{- end }}
    {{- if .Values.ingress.public.oauth2ProxyProtected }}
    nginx.ingress.kubernetes.io/auth-signin: https://oauth2.{{ .Values.ingress.clusterDomain }}/oauth2/start?rd=https%3A%2F%2F$http_host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://oauth2.{{ .Values.ingress.clusterDomain }}/oauth2/auth
    {{- end }}
spec:
  ingressClassName: nginx-public
  rules:
  {{- range $host := (concat (list (include "get-ingress-primary-public-host" .)) .Values.ingress.public.additionalHosts) }}
    - host: {{ $host }}
      http:
        paths:
        {{- if $.Values.ingress.public.paths.allowAll }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.serviceName }}
                port:
                  number: 80
        {{- else }}
          {{- range $prefix := $.Values.ingress.public.paths.prefixes }}
          {{- if eq $prefix "/" -}}
            {{- fail "Prefixes may not contain /, please set allowAll: true explicitly!" -}}
          {{- end }}
          - path: {{ $prefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.serviceName }}
                port:
                  number: 80
          {{- end }}
          {{- range $exact := $.Values.ingress.public.paths.exact }}
          - path: {{ $exact }}
            pathType: Exact
            backend:
              service:
                name: {{ $.Values.serviceName }}
                port:
                  number: 80
          {{- end }}
        {{- end }}
  {{- end}}
{{- end }}
