apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}
  namespace: "{{ required "Namespace must be set!" .Values.namespace }}"
  annotations:
    {{- if .Values.ingress.overwriteCustomHttpErrors }}
    nginx.ingress.kubernetes.io/custom-http-errors: {{ .Values.ingress.overwriteCustomHttpErrors }}
    {{- end }}
    {{- if .Values.ingress.overwriteProxyReadTimeout }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.overwriteProxyReadTimeout }}
    {{- end }}
    {{- if .Values.ingress.overwriteCustomBodySize }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.overwriteCustomBodySize }}
    {{- end }}
    {{- if .Values.ingress.basicAuthSecretParameterName }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.serviceName }}-external-secret
    nginx.ingress.kubernetes.io/auth-realm: {{ .Values.serviceName }}
    {{- end }}
spec:
  rules:
    - host: {{ required "Ingress Host must be set!" .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.serviceName }}
              servicePort: 80
