kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.serviceName }}
  namespace: "{{ required "Namespace must be set!" .Values.namespace }}"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.serviceName }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
