{{- if false }}
{{/* Enable me with v2.0.0 */}}
{{- range $authorization := .Values.route.public.authorization }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-public-{{ if eq $authorization.type "oauth2" }}oauth2{{ else }}{{ required "Special authorization needs a name" $authorization.name | lower }}{{ end }}
  namespace: "istio-system"
  # must use the gateway namespace unless L7 proxies are available (afaiu waypoints or sidecar mode)
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mp-public
  {{- if eq $authorization.type "oauth2 "}}
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              {{- range $host := .Values.route.public.hostnames }}
              - {{ include "validate-hostname" (replace "$clusterDomain" .Values.route.clusterDomain $host) }}
              {{- end }}
  {{- else if has $authorization.type (list "ALLOW" "DENY") }}
  action: {{ $authorization.type }}
  rules:
  {{- range $rule := $authorization.rules }}
    - {{ toYaml $rule }}
      to:
        - operation:
            hosts:
              {{- range $host := .Values.route.public.hostnames }}
              - {{ include "validate-hostname" (replace "$clusterDomain" .Values.route.clusterDomain $host) }}
              {{- end }}
  {{- end }}
  {{- else }}
    {{ fail (printf "Unknown authorization type: %s" $authorization.type) }}
  {{- end }}
{{- end }}
{{- end }}
