{{- if .Values.ingress.public.oauth2ProxyProtected }}
{{- $primaryPublicHost := include "get-httproute-primary-public-host" . }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-oauth2-public
  namespace: "istio-system"
  # must use the gateway namespace unless L7 proxies are available (afaiu waypoints or sidecar mode)
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: mp-public
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts:
              - {{ include "validate-hostname" $primaryPublicHost }}
              {{- range $host := .Values.ingress.public.additionalHosts }}
              - {{ include "validate-hostname" $host }}
              {{- end }}
{{- end }}
