{{- if (ne (include "is-public-httproute-defined" .) "false") }}
{{- $primaryPublicHost := include "get-httproute-primary-public-host" . }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-public
  namespace: "{{ .Release.Namespace }}"
spec:
  parentRefs:
    - name: mp-public
      namespace: istio-system
      sectionName: https-public
  hostnames:
    - {{ include "get-validated-hostname" $primaryPublicHost }}
    {{- range $host := .Values.ingress.public.additionalHosts }}
    - {{ include "get-validated-hostname" $host }}
    {{- end }}
  rules:
  - matches:
    {{- if .Values.ingress.public.paths.allowAll }}
    - path:
        type: PathPrefix
        value: /
    {{- else }}
    {{- range $prefix := .Values.ingress.public.paths.prefixes }}
    {{- if eq $prefix "/" }}
    {{- fail "Prefixes may not contain /, please set allowAll: true explicitly!" }}
    {{- end }}
    - path:
        type: PathPrefix
        value: {{ $prefix }}
    {{- end }}
    {{- range $exact := .Values.ingress.public.paths.exact }}
    - path:
        type: Exact
        value: {{ $exact }}
    {{- end }}
    {{- end }}
    backendRefs:
      - name: {{ .Release.Name }}
        port: 80
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        remove:
          - "Server"
          - "X-Application-Context"
          - "X-Powered-By"
          - "Strict-Transport-Security"
          - "Content-Security-Policy"
          - "X-Content-Type-Options"
          - "Referrer-Policy"
          - "X-Robots-Tag"
        add:
          # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
          # frame-ancestors are allowed to embed iframes from microfrontends.<clusterDomain> into the application on <clusterDomain>
          - name: "Content-Security-Policy"
            value: "frame-ancestors 'self' {{ .Values.ingress.clusterDomain }}"
          # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options
          - name: "X-Content-Type-Options"
            value: "nosniff"
          # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
          - name: "Referrer-Policy"
            value: "strict-origin-when-cross-origin"
          # See https://developers.google.com/search/docs/crawling-indexing/robots-meta-tag?hl=de#directives
          - name: "X-Robots-Tag"
            value: "noindex, nofollow"
          # See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security
          - name: "Strict-Transport-Security"
            value: "max-age=31536000; includeSubDomains; preload"

{{- end }}
