apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: "{{ .Values.namespace }}"
  labels:
    app: kube-prometheus-stack
    release: prometheus
  name: "{{ .Values.cronJobName }}"
spec:
  groups:
{{- if or .Values.alertingRules .Values.additionalAlertingRules }}
    - name: "{{ .Values.cronJobName }}"
      rules:
        {{- range $key, $value := .Values.alertingRules }}
        - alert: "{{ $.Values.cronJobName }}_{{ $key }}"
          expr: {{ $value.expr | quote }}
          {{- if $value.for }}
          for: {{ $value.for | quote }}
          {{- end }}
          labels:
            service: {{ $.Values.cronJobName | quote }}
            namespace: {{ $.Values.namespace | quote }}
          annotations:
            description: {{ required "Description must be set!" .description | quote }}
            playbook_url: {{ required "Playbook URL must be set!" .playbook_url | quote }}
            {{- range $key, $value := .extraAnnotations }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
        {{- end }}
{{- end }}
