name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  checks: write
  contents: write
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.7.0
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - run: make test

  remind-of-release-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      with:
        fetch-depth: 0
    - run: |
        echo "MEISTERPLAN_SERVICE_CHART_VERSION=$(grep -Po '(?<=version: )[0-9.]+' charts/meisterplan-service/Chart.yaml)" >> "$GITHUB_ENV"
        echo "CRONJOB_CHART_VERSION=$(grep -Po '(?<=version: )[0-9.]+' charts/cronjob/Chart.yaml)" >> "$GITHUB_ENV"
    - run: |
        git show-ref --tags --verify --quiet "refs/tags/meisterplan-service-${MEISTERPLAN_SERVICE_CHART_VERSION}" && \
            echo "MEISTERPLAN_SERVICE_EXISTS=true" || echo "MEISTERPLAN_SERVICE_EXISTS=false" >> "$GITHUB_ENV"
        git show-ref --tags --verify --quiet "refs/tags/cronjob-${CRONJOB_CHART_VERSION}" && \
            echo "CRONJOB_EXISTS=true" || echo "CRONJOB_EXISTS=false" >> "$GITHUB_ENV"
    - uses: marocchino/sticky-pull-request-comment@f61b6cf21ef2fcc468f4345cdfcc9bda741d2343 # v2.6.2
      with:
        message: |
          Merging this PR will attempt to deploy these Charts (existing versions will be skipped):
          ${{ env.MEISTERPLAN_SERVICE_EXISTS == 'false' && format('* meisterplan-service **{0}**', env.MEISTERPLAN_SERVICE_CHART_VERSION) || '' }}
          ${{ env.CRONJOB_EXISTS == 'false' && format('* cronjob **{0}**', env.CRONJOB_CHART_VERSION) || '' }}

  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.7.0

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: helm/chart-releaser-action@c25b74a986eb925b398320414b576227f375f946 # v1.2.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
