{{- if and .Values.platform.spring.env.datasourceFromSecret .Values.platform.spring.env.datasourceFromSecretWithRLS }}
{{ fail "You cannot set both springDatasourceFromSecret and springDatasourceFromSecretWithRLS at the same time" }}
{{- end}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  data:
    {{- if .Values.sentry.enabled }}
    - secretKey: "SENTRY_DSN"
      remoteRef:
        key: "/{{ required "envName must be set!" .Values.envName }}/sentry/dsn-{{ .Release.Name }}"
    {{- end }}
    {{ include "get-platform-secret-keys" . | indent 4 }}
  {{- range $key, $value := .Values.podConfiguration.env.fromSecret }}
    - secretKey: "{{ $key }}"
      remoteRef:
        key: "/{{ $.Values.envName }}/{{ $value.parameterName }}"
  {{- end }}
